channels:
    - anaconda
    - conda-forge
dependencies:
    - python=3.6
    - yaml=0.1.7
    - pyyaml=5.1.1
    - matplotlib
    - pandas
    - numpy
    - tqdm
    - scikit-image
    - pytorch::pytorch=1.6.0
    - pytorch::torchvision=0.7.0
    - cudatoolkit=10.1
    - pip
    - pip:
        - tensorboardX
