TRAIN:
    model: singlepath
    workers: 15
    batch_size: 1024
    epochs: 160

    lr_mode : cosine
    base_lr: 0.34
    targetlr: 0.0
    power: 1
    warmup_mode: linear
    warmup_lr: 0.0001
    warmup_epochs: 0

    momentum: 0.9
    weight_decay: 0.00004

    using_moving_average : True
    last_gamma : True
    using_bn: True

    print_freq: 100
    model_dir: ckpts_1_5_x
    checkpoint_path: 2020-10-29/search-EXP-20201029-100813-imagenet_epo_240_layer_20_batch_1024_lr_0.5_seed_48_pretrain_15_early_fix_arch_flops_loss_1e-06_search_arch_lr_1e-3_decay_0/model-best.pth

    train_root: /nvme1/datasets/ilsvrc2012/train
    train_source: /nvme1/datasets/ilsvrc2012/train.txt
    val_root: /nvme1/datasets/ilsvrc2012/val
    val_source: /nvme1/datasets/ilsvrc2012/val.txt
